#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

# unset to configure only via envvars
# ND_CONFIGFILE=${ND_CONFIGFILE:-/data/navidrome.toml}; # set in Dockerfile
ND_DATAFOLDER="${ND_DATAFOLDER:-/data}";
# NAVIDROME_ARGS="${NAVIDROME_ARGS:-}";

cd ${ND_DATAFOLDER} || exit 1;

usercmd \
exec \
    navidrome \
    ${ND_CONFIGFILE:+ --configfile $ND_CONFIGFILE } \
    ${NAVIDROME_ARGS};
